//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__flatten__11.h"
#include "tracing.h"
#include "utils.h"

void
free_operator__ai_onnx__flatten__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */


    TRACE_EXIT(1);
}