//this file was generated by ../../../../../../scripts/onnx_generator/OperatorTemplate.py
#include "operator__ai_onnx__gemm__11.h"
#include "tracing.h"
#include "utils.h"
// #include <string.h>

operator_status
prepare_operator__ai_onnx__gemm__11(
    node_context *ctx
)
{
    TRACE_ENTRY(1);

    TRACE_NODE(2, true, ctx->onnx_node);

    /* UNCOMMENT AS NEEDED */

    Onnx__TensorProto *i_A = searchInputByName(ctx, 0);
    Onnx__TensorProto *i_B = searchInputByName(ctx, 1);
    Onnx__TensorProto *i_C = searchInputByName(ctx, 2);
    // Onnx__TensorProto *i_B = searchInputByName(ctx, 2);

    TRACE_TENSOR(2, true, i_A);
    TRACE_TENSOR(2, true, i_B);
    TRACE_TENSOR(2, true, i_C);

    Onnx__AttributeProto *a_alpha  = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"alpha");
    Onnx__AttributeProto *a_beta   = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"beta");
    Onnx__AttributeProto *a_transA = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"transA");
    Onnx__AttributeProto *a_transB = searchAttributeNyName(ctx->onnx_node->n_attribute,ctx->onnx_node->attribute,"transB");

    TRACE_ATTRIBUTE(2, a_alpha,  a_alpha);
    TRACE_ATTRIBUTE(2, a_beta,   a_beta);
    TRACE_ATTRIBUTE(2, a_transA, a_transA);
    TRACE_ATTRIBUTE(2, a_transB, a_transB);

    Onnx__TensorProto *o_Y = searchOutputByName(ctx, 0);

    /* ALLOCATE AND INITIALIZE CONTEXT HERE IF NEEDED */

    // W : (M x C/group x K1 x K2 x ... )
    int K  = i_A->dims[0];
    int N  = i_C->dims[0];

    float  default_alpha = 1.0f;
    float  default_beta  = 0.0f;
    size_t default_transA = 0;
    size_t default_transB = 0;

    context_operator__ai_onnx__gemm__11 *op_ctx = NULL;
    op_ctx = (context_operator__ai_onnx__gemm__11*)malloc(sizeof(context_operator__ai_onnx__gemm__11));
    TRACE_FATAL(0 , !op_ctx, "could not allocate executer_context");


    op_ctx->K     = K;
    op_ctx->N     = N;

    op_ctx->alpha  = a_alpha? a_alpha->f :default_alpha;
    op_ctx->beta   = a_beta?  a_beta->f  :default_beta;
    op_ctx->transA = a_transA?a_transA->i:default_transA;
    op_ctx->transB = a_transB?a_transB->i:default_transB;

    /* INITIALIZE OUTPUTS DATA_TYPE AND SHAPE HERE */

    o_Y->n_dims = 1;
    o_Y->dims   = (int64_t*)malloc(o_Y->n_dims * sizeof(int64_t));


    o_Y->dims[0] = N;
    o_Y->has_raw_data = 0;
    o_Y->data_type    = i_A->data_type;

    /* MALLOC OUTPUT TENSORS HERE */

    mallocTensorData(o_Y);

    TRACE_TENSOR(2, true, o_Y);

    /* CHOOSE EXECUTER AND CONTEXT HERE */
    /* YOU MAY USE THE GENERATED RESOLVER */

    ctx->executer = resolve_operator__ai_onnx__gemm__11(ctx);
    ctx->executer_context = op_ctx;

    TRACE_EXIT(1);

    /* CHANGE RETURN CODE IF THIS PREPARER IS VALID */
    // return OP_ENOSYS;
    return OP_OK;
}